spring.application.name=one-store


spring.datasource.url=jdbc:postgresql://ep-shy-silence-a185zm7a-pooler.ap-southeast-1.aws.neon.tech/neondb
spring.datasource.username=neondb_owner
spring.datasource.password=npg_8inoW0IvNCGw
spring.jpa.hibernate.ddl-auto=none
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

